import { TrendingList } from "../components/TrendingList";
import { NewsletterSignup } from "../components/NewsletterSignup";

// This reads from the static JSON generated by the pipeline
async function getTrendingData() {
  try {
    const data = await import("../lib/data/trending.json");
    return data.default || data;
  } catch {
    return null;
  }
}

export default async function Home() {
  const data = await getTrendingData();

  return (
    <main className="min-h-screen">
      {/* Header */}
      <header className="border-b border-gray-100">
        <div className="max-w-2xl mx-auto px-4 py-8">
          <h1 className="text-3xl font-bold tracking-tight">
            SF Trending Eats
          </h1>
          <p className="mt-2 text-gray-500 text-lg">
            Bay Area restaurants trending on social media this week
          </p>
        </div>
      </header>

      {/* Main content */}
      <div className="max-w-2xl mx-auto px-4 py-8">
        {data ? (
          <>
            <p className="text-sm text-gray-400 mb-8">
              Week of {data.week_start} · Updated{" "}
              {new Date(data.generated_at).toLocaleDateString()}
            </p>
            <TrendingList restaurants={data.restaurants} />
          </>
        ) : (
          <div className="text-center py-16">
            <p className="text-gray-400 text-lg">
              First trending list coming soon.
            </p>
            <p className="text-gray-400 mt-2">
              Sign up below to get notified when it drops.
            </p>
          </div>
        )}

        {/* Newsletter signup */}
        <div className="mt-16 pt-8 border-t border-gray-100">
          <NewsletterSignup />
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-gray-100 mt-16">
        <div className="max-w-2xl mx-auto px-4 py-8 text-center text-sm text-gray-400">
          <p>
            SF Trending Eats tracks social media signals across Yelp, Reddit,
            Threads, Google, and more to surface restaurants that are trending
            before they hit mainstream food media.
          </p>
          <p className="mt-4">
            Built with data, not opinions.
          </p>
        </div>
      </footer>
    </main>
  );
}
